### ISSUE TITLE
docs: use files directory instead of config directory

### ISSUE THREAD

**Issue by notnotno** [blue-build/website#59]
The website documentation still mentions using the config/files directory, but the bluebuild client gives this warning:  "WARN  => Use of the ./config directory is deprecated. Please move your non-recipe files into ./files".

Also including clarification for the following would be helpful:
- Is simply renaming 'config' directory to 'files'  is all that's needed?
- For the files module, would they be placed in files/files or just /files?

**Comment by fiftydinar** [comment]
@notnotno It currently does mostly work, since the preliminary work is done in BlueBuild CLI regarding this.

Only `gschema-overrides` module won't work, which has hardcoded path to `config/`.

But we also changed `files` module to conform to this new `files/` location, so it can use any location of choice in `files/` instead of being hardcoded to `files/files/` in your case.

It took some time until we fully investigated & decided on how this transition from `config/` to `files/` will finally look.

Hence why we didn't make docs about this yet.

**Comment by xynydev** [comment]
This issue seems to just have been forgotten to be closed. See https://blue-build.org/blog/config-files/
